// Generated by the art script: the sprite files present under
// apps/web/public/expedition/sprites/, relative to that folder. Lists only
// files on disk so the browser never requests a missing sprite.
export const ART_FILES: readonly string[] = [];
